name: Wiki Builder

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: Saber2pr/wiki-builder@v0.0.88
        with:
          cname: saber2pr.top
          ignoreCnameFile: true
          basename: /zh
          gaId: G-6CLMYWGQBH
          gaAdId: ca-pub-3641373095149503
          gaAdsTxt: google.com, pub-3641373095149503, DIRECT, f08c47fec0942fa0
          gaAdsSlotHtml: <ins class="adsbygoogle" style="display:block; text-align:center;" data-ad-layout="in-article" data-ad-format="fluid" data-ad-client="ca-pub-3641373095149503" data-ad-slot="5932086556"></ins>
          iconUrl: //saber2pr.top/MyWeb/resource/image/saber2pr-top.ico
          i18nConfig: '[{"name":"Chinese","key":"/zh"},{"name":"English","key":"/"}]'
          buttomlinksUri: https://saber2pr.top/zh/links.json?ts=1301
